### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by ChronoWeaver** [SeekingLight233/chatgpt-bookmarks#1]
按照设置方法设置后，进入ChatGPT界面后，网页无任何变化

**Comment by SeekingLight233** [comment]
> 按照设置方法设置后，进入ChatGPT界面后，网页无任何变化

F12看下是否有报错信息？麻烦提供一下

**Comment by ChronoWeaver** [comment]
<img width="562" alt="截屏2023-10-29 10 53 01" src="https://github.com/SeekingLight233/chatgpt-bookmarks/assets/101154423/de9b9af4-b30a-48f9-aead-96a4c5850591">

不知道这个issue和您的插件是否有关系
我插件启动后，ChatGPT的界面并没有改变

**Comment by SeekingLight233** [comment]
> <img alt="截屏2023-10-29 10 53 01" width="562" src="https://user-images.githubusercontent.com/101154423/278848366-de9b9af4-b30a-48f9-aead-96a4c5850591.png">
> 不知道这个issue和您的插件是否有关系 我插件启动后，ChatGPT的界面并没有改变

我尝试使用mac和windows下最新的chrome版本，目前均正常
请提供一下您的操作系统信息和chrome版本
同时我注意到控制台报了一个Unable to load account的info
您尝试退出重新登录下试试

**Comment by ChronoWeaver** [comment]
已经尝试退出账号重新登陆，并更新chrome为最新版（版本 118.0.5993.117（正式版本） (arm64)），仍然有问题
我使用的是m1芯片的macbookpro 

<img width="737" alt="截屏2023-10-29 20 32 03" src="https://github.com/SeekingLight233/chatgpt-bookmarks/assets/101154423/84a83ba4-d4e6-451e-ac4f-0dc9b501fc12">

**Comment by ChronoWeaver** [comment]
今天打开之后突然就可以用了，再次感谢您的耐心回答，如果以后加入可以把问题也加入notion的功能就更好了，再次感谢。

**Comment by SeekingLight233** [comment]
> 今天打开之后突然就可以用了，再次感谢您的耐心回答，如果以后加入可以把问题也加入notion的功能就更好了，再次感谢。

嗯嗯，可能是因为网络原因没有加载出来脚本文件

问题是默认会放到标题框中的，目前的版本存在bug，新版本正在审核
